### ISSUE TITLE
Invalid SSML: Content is not allowed in prolog.

### ISSUE THREAD

**Issue by benlangfeld** [rayo/rayo-server#1]
https://gist.github.com/df2e005ebfac8e8b34f7

**Comment by benlangfeld** [comment]
Subscribing @polysics

**Comment by mpermar** [comment]
There is a problem when using recognizers other than 'en-us'

I've opened an internal ticket for tracking this issue with the Prism team: https://evolution.voxeo.com/ticket/1532827

Will update here when fixed.

**Comment by mpermar** [comment]
This one is already fixed. Any Prism build from October onwards should be ok.
