### ISSUE TITLE
XMPP listener starts before being ready to process requests

### ISSUE THREAD

**Issue by bklang** [rayo/rayo-server#13]
This is probably an issue for PRISM more than Rayo Server.

When starting up PRISM, the XMPP port is opened (socket is listening) before it is actually able to process a request, such as an XMPP login.  This results in clients hanging, sometimes indefinitely.   The message is apparently discarded: even though the client has an active TCP connection, but the eventual XMPP service inside PRISM never receives the message.  I would request that any messages that hit the socket should be returned with an XMPP error code until something is available to handle the request.

**Comment by mpermar** [comment]
This is indeed a Prism issue. I've opened an internal ticket for it: https://evolution.voxeo.com/ticket/1641162

Also, bear in mind that in Rayo you should not connect directly to the Prism server but to an XMPP Server or to a Rayo Gateway instead.
