### ISSUE TITLE
Unable to match full SIP URIs in rayo-routing.properties

### ISSUE THREAD

**Issue by bklang** [rayo/rayo-server#14]
I wanted to match an exact SIP username for routing to a specific JID.  I tried the following combinations, but the Rayo server never reported a match:

```
sip:arabbit@.*=arabbit@127.0.0.1
sip:arabbit.*=arabbit@127.0.0.1
arabbit@.*=arabbit@127.0.0.1
arabbit.*=arabbit@127.0.0.1
```

The logs make it appear that the string to be matched is "sip:arabbit@127.0.0.1", based on the error message `We didn't find any Regexp match for sip:arabbit@127.0.0.1`

**Comment by mpermar** [comment]
Good catch! It is fixed now. Note you could have used something like `.*arabbit.*=arabbit@127.0.0.1`
