### ISSUE TITLE
JID routing does not work with non-standard SIP ports

### ISSUE THREAD

**Issue by benlangfeld** [rayo/rayo-server#8]
Running rayo on 5061 results in a breakdown of the regex-based routing. May be a documentation issue.

**Comment by mpermar** [comment]
Sorry, tested it and it actually does work. It could be a matter of the regexp expression you were using. But something like this will work:

.*=usera@localhost 

or even this one should work:

.*:5061=usera@localhost

Be also aware that order does matter. So a rule on the top of the list can easily be overriding other rules below
